# Generated by Django 3.2.6 on 2021-09-11 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20210911_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.products'),
        ),
    ]
