# Generated by Django 3.2.6 on 2021-09-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_auto_20210911_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
