# Generated by Django 3.2.6 on 2021-09-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
