# Generated by Django 3.2.6 on 2021-09-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(default=2, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(default=45, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image4',
            field=models.ImageField(default=85, upload_to='pics'),
            preserve_default=False,
        ),
    ]
