# Generated by Django 3.2.6 on 2021-10-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_auto_20210915_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=255, unique=True)),
                ('percentage', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('expiry_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.offer'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.offer'),
        ),
    ]
