# Generated by Django 3.2.6 on 2021-10-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_products_product_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_offer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_offer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
