# Generated by Django 3.2.6 on 2021-10-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_auto_20211002_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
