# Generated by Django 3.2.6 on 2021-10-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_products_offer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=255, unique=True)),
                ('coupon_code', models.UUIDField()),
                ('percentage', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('expiry_time', models.TimeField()),
            ],
        ),
    ]
