# Generated by Django 3.2.6 on 2021-10-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_name',
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimal_rate',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
