# Generated by Django 3.2.6 on 2021-10-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_user_coupon_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_coupon',
            name='offer_amount',
        ),
    ]
