# Generated by Django 3.2.6 on 2021-09-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_delete_cart'),
        ('userlogin', '0002_alter_cart1_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart1',
            new_name='cart',
        ),
    ]
