# Generated by Django 3.2.6 on 2021-09-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_rename_cart1_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='guset_token',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_name',
            field=models.IntegerField(blank=True),
        ),
    ]
