# Generated by Django 3.2.6 on 2021-09-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0004_auto_20210912_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='guset_token',
            new_name='guest_token',
        ),
    ]
