# Generated by Django 3.2.6 on 2021-09-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0005_rename_guset_token_cart_guest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
