# Generated by Django 3.2.6 on 2021-09-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0006_alter_cart_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
