# Generated by Django 3.2.6 on 2021-09-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0008_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phn_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(max_length=2500),
        ),
    ]
