# Generated by Django 3.2.6 on 2021-09-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0009_auto_20210914_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlogin.address')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlogin.cart')),
            ],
        ),
    ]
