# Generated by Django 3.2.6 on 2021-09-15 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0011_orders_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userlogin.address'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userlogin.cart'),
        ),
    ]
