# Generated by Django 3.2.6 on 2021-09-15 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0012_auto_20210915_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userlogin.address'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userlogin.cart'),
        ),
    ]
