# Generated by Django 3.2.6 on 2021-09-15 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_delete_orders'),
        ('userlogin', '0013_auto_20210915_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user_cart',
        ),
        migrations.AddField(
            model_name='orders',
            name='products_id',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=41),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlogin.address'),
        ),
    ]
