# Generated by Django 3.2.6 on 2021-10-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0018_userimage_referal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='wallet_cash',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userimage',
            name='profileimage',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
