# Generated by Django 3.2.6 on 2021-10-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0019_auto_20211005_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='referal_code',
            new_name='referral_code',
        ),
    ]
