# Generated by Django 3.2.6 on 2021-10-06 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0015_auto_20211002_1857'),
        ('userlogin', '0020_rename_referal_code_userimage_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_wishlist', models.UUIDField(null=True)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.products')),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
