# Generated by Django 3.2.6 on 2021-10-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0021_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='mobile_num',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
