# Generated by Django 3.2.6 on 2021-10-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0022_userimage_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='mobile_num',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
