# Generated by Django 3.2.6 on 2021-10-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0023_alter_userimage_mobile_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
