# Generated by Django 3.2.6 on 2021-10-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0024_userimage_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='mobile_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
